[markup]
[markup.highlight]
    lineNos = true
    tabWidth = 4
    noClasses = false

[mediaTypes]
[mediaTypes."application/atom+xml"]
    suffixes = [ "xml", "atom" ]

[outputFormats]
[outputFormats.rss]
    baseName = "rss"
    isHTML = false
    isPlainText = false
    mediaType = "application/rss+xml"
    noUgly = true
    permalinkable = false
    rel = "alternate"
[outputFormats.atom]
    baseName = "atom"
    isHTML = false
    isPlainText = false
    mediaType = "application/atom+xml"
    noUgly = true
    notAlternative = false
    permalinkable = false
    rel = "alternate"


[module]
[module.hugoVersion]
    extended = false
    min = "0.158.0"
